version: '3.7'

services:
  frontend:
    container_name: ng_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: ng_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_CONN_STR=mongodb://mongodb-svc:27017/todo?directConnection=true
      - MONGO_USERNAME_FILE=/run/secrets/mongo_username
      - MONGO_PASSWORD_FILE=/run/secrets/mongo_password
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
    secrets:
      - mongo_username
      - mongo_password
    healthcheck:
      test: ["CMD", "node", "-e", "require('mongodb').MongoClient.connect(process.env.MONGO_CONN_STR, { useUnifiedTopology: true }, err => process.exit(err ? 1 : 0));"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    command:
      - "numactl"
      - "--interleave=all"
      - "mongod"
      - "--wiredTigerCacheSizeGB"
      - "0.1"
      - "--bind_ip"
      - "0.0.0.0"
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    secrets:
      - mongo_username
      - mongo_password

volumes:
  mongo-data:

secrets:
  mongo_username:
    file: ./secrets/mongo_username.txt
  mongo_password:
    file: ./secrets/mongo_password.txt
